# Generated by Django 3.0.7 on 2021-04-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='if_interested',
            field=models.BooleanField(default=True),
        ),
    ]
